name: Auto-merge all device branches

on:
  push:
    branches:
    - "device/cerebro"

permissions:
  contents: "write"

jobs:
  sync:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - name: "Update device branches"
        shell: "bash"
        run: |
          set -eEuo pipefail
          main="$(git rev-parse --abbrev-ref HEAD)"
          git fetch --all
          for branch in "$(git for-each-ref --format='%(refname:short)' refs/heads/device/)"
          do
            if test "$branch" != "$main"
            then
              git checkout "$branch"
              git merge "$main"
              git push origin "$branch"
            fi
          done
