name: Auto-merge all device branches

on:
  push:
    branches:
    - "device/cerebro"

permissions:
  contents: "write"

jobs:
  sync:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - name: "Update device branches"
        shell: "bash"
        run: |
          set -eEuo pipefail
          main="$(git rev-parse --abbrev-ref HEAD)"
          echo "Main branch: $main"
          readarray -t branches <<< $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/device/)
          for branch in "${branches[@]}"
          do
            branch="${branch#origin/}"
            echo "Checking $branch"
            if echo "$branch" | grep -xv -e "$main" -e "HEAD"
            then
              git checkout "$branch"
              echo "Checked out branch: $branch"
              git merge "$main"
              echo "Merged $main branch into $branch"
              git push origin "$branch"
              echo "Pushed $branch"
            else
              echo "Skipping $branch (default or HEAD)"
            fi
          done
          echo "All device branches updated"
