name: Automatically merge device/cerebro into all device branches

on:
  push:
    branches:
    - "device/cerebro"

env:
  USERNAME: "github-actions[bot]"
  EMAIL: "64036239+bswck@users.noreply.github.com"

permissions:
  contents: "write"

jobs:
  merge-all:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - name: "Update device branches"
        shell: "bash"
        run: |
          set -eEuo pipefail
          git config user.name "$USERNAME"
          git config user.email "$EMAIL"
          main="$(git rev-parse --abbrev-ref HEAD)"
          echo "Main branch: $main"
          readarray -t branches <<< $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/device/)
          for branch in "${branches[@]}"
          do
            branch="${branch#origin/}"
            echo "Checking $branch"
            if echo "$branch" | grep -xv -e "$main" -e "HEAD"
            then
              git checkout "$branch"
              echo "Checked out branch: $branch"
              set +e
              git merge "$main" \
              && git pull \
              && echo "Merged $main branch into $branch" \
              && git push origin "$branch" \
              && echo "Pushed $branch"
              set -e
            else
              echo "Skipping $branch (default or HEAD)"
            fi
          done
          echo "All device branches updated"
